### PR TITLE
Migrated `adminonly` commands to slash commands

### PR DESCRIPTION
**Pull request by ghost**
Started work on migrating the `adminonly` commands over to slash commands, as well as fixing logic where possible.

### CODE REVIEW

**Comment by ghost** [comment]
If you take the slash command builders and use things like `.setMinValue()` and `.setMaxValue()` on the slash command options, you can set the minimum/maximum amount of text or the minimum/maximum integer allowed. It makes it easy cause then the bot doesn't reply to the user, Discord blocks the slash command.

**Comment by The-Bunny-Official** [comment]
I'm also going to move this pull request to a new branch called "v3-dev". Just so that we can keep the v2 code if anything goes crazy.

**Comment by ghost** [comment]
I have committed changes to utilize those options, removing the need of extra logic within the command itself.

**Review by ghost — APPROVED** [review]
These look good, thank you!

**Pull request merged**
